# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(default=None, max_length=256)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('producer', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=128)),
                ('appellation', models.CharField(max_length=256)),
                ('vintage', models.CharField(max_length=128)),
                ('importer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importers', to='wineapp.Importer')),
            ],
        ),
    ]
